import { useEffect, useMemo, useRef } from "react";
import * as THREE from "three";
import type { CardInstance } from "@ward/shared";
import type { AppMatchState } from "../../clientTypes";
import type { BoardObject } from "../boardPreview3dAdapter";
import { getMatchCardImageUrls } from "../MatchCardImage";

type BoardPreview3DWebGLCardsProps = {
  cardByInstanceId: Map<string, CardInstance>;
  filteredBoardObjects: BoardObject[];
  heightScale: number;
  match: AppMatchState;
  resolveSlotPosition: (slotId: string, fallbackX: number, fallbackZ: number) => { xPercent: number; zPercent: number };
};

const CARD_WORLD_WIDTH = 128;
const CARD_WORLD_HEIGHT = 179;
const cardTextureCache = new Map<string, Promise<THREE.Texture | null>>();

type ViewMetrics = {
  height: number;
  width: number;
  worldHeight: number;
  worldWidth: number;
};

function createCardBackTexture(): THREE.CanvasTexture {
  const canvas = document.createElement("canvas");
  canvas.width = 512;
  canvas.height = 716;
  const context = canvas.getContext("2d");

  if (context) {
    const gradient = context.createLinearGradient(0, 0, canvas.width, canvas.height);
    gradient.addColorStop(0, "#0f172a");
    gradient.addColorStop(0.5, "#082f49");
    gradient.addColorStop(1, "#020617");
    context.fillStyle = gradient;
    context.fillRect(0, 0, canvas.width, canvas.height);
    context.strokeStyle = "rgba(125, 211, 252, 0.72)";
    context.lineWidth = 18;
    context.strokeRect(28, 28, canvas.width - 56, canvas.height - 56);
    context.strokeStyle = "rgba(250, 204, 21, 0.42)";
    context.lineWidth = 8;
    context.strokeRect(58, 58, canvas.width - 116, canvas.height - 116);
    context.fillStyle = "rgba(226, 232, 240, 0.92)";
    context.font = "900 54px system-ui, sans-serif";
    context.textAlign = "center";
    context.textBaseline = "middle";
    context.fillText("Ward", canvas.width / 2, canvas.height / 2 - 34);
    context.fillText("Nexus", canvas.width / 2, canvas.height / 2 + 34);
  }

  const texture = new THREE.CanvasTexture(canvas);
  texture.colorSpace = THREE.SRGBColorSpace;
  texture.generateMipmaps = true;
  texture.minFilter = THREE.LinearMipmapLinearFilter;
  texture.magFilter = THREE.LinearFilter;
  texture.anisotropy = 8;
  texture.needsUpdate = true;
  return texture;
}

function configureTexture(texture: THREE.Texture, renderer: THREE.WebGLRenderer): THREE.Texture {
  texture.colorSpace = THREE.SRGBColorSpace;
  texture.generateMipmaps = true;
  texture.minFilter = THREE.LinearMipmapLinearFilter;
  texture.magFilter = THREE.LinearFilter;
  texture.anisotropy = renderer.capabilities.getMaxAnisotropy();
  texture.needsUpdate = true;
  return texture;
}

async function loadCardTexture(urls: string[], loader: THREE.TextureLoader, renderer: THREE.WebGLRenderer): Promise<THREE.Texture | null> {
  for (const url of urls) {
    try {
      let cached = cardTextureCache.get(url);
      if (!cached) {
        cached = loader.loadAsync(url).then(texture => configureTexture(texture, renderer)).catch(() => null);
        cardTextureCache.set(url, cached);
      }
      const texture = await cached;
      if (texture) return texture;
    } catch {
      // Try the next candidate generated by MatchCardImage.
    }
  }

  return null;
}

function createPlane(texture: THREE.Texture, width: number, height: number): THREE.Mesh {
  const geometry = new THREE.PlaneGeometry(width, height);
  const material = new THREE.MeshBasicMaterial({
    map: texture,
    side: THREE.DoubleSide,
    toneMapped: false,
    transparent: true
  });
  const mesh = new THREE.Mesh(geometry, material);
  return mesh;
}

export function BoardPreview3DWebGLCards({
  cardByInstanceId,
  filteredBoardObjects,
  heightScale,
  match,
  resolveSlotPosition
}: BoardPreview3DWebGLCardsProps) {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const latestRenderDataRef = useRef({
    cardByInstanceId,
    filteredBoardObjects,
    match,
    resolveSlotPosition
  });
  latestRenderDataRef.current = {
    cardByInstanceId,
    filteredBoardObjects,
    match,
    resolveSlotPosition
  };
  const renderSignature = useMemo(
    () => filteredBoardObjects
      .map(object => {
        const renderedCard = object.cardInstanceId ? cardByInstanceId.get(object.cardInstanceId) ?? null : null;
        const urls = renderedCard ? getMatchCardImageUrls(match, renderedCard).join(",") : "";
        return [
          object.id,
          object.slotId,
          object.lane,
          object.cardInstanceId ?? "back",
          object.xPercent.toFixed(3),
          object.zPercent.toFixed(3),
          object.yDepth.toFixed(3),
          urls
        ].join(":");
      })
      .join("|"),
    [cardByInstanceId, filteredBoardObjects, match]
  );

  useEffect(() => {
    const canvas = canvasRef.current;
    const parent = canvas?.parentElement;
    if (!canvas || !parent) return;

    let isDisposed = false;
    const renderer = new THREE.WebGLRenderer({
      alpha: true,
      antialias: true,
      canvas,
      powerPreference: "high-performance"
    });
    renderer.outputColorSpace = THREE.SRGBColorSpace;
    renderer.setClearColor(0x000000, 0);
    renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, 2.5));

    const scene = new THREE.Scene();
    const camera = new THREE.OrthographicCamera(
      -1,
      1,
      1,
      -1,
      0.1,
      1000
    );
    const loader = new THREE.TextureLoader();
    let renderedMeshes: THREE.Mesh[] = [];
    let renderRequestId = 0;
    const backTexture = createCardBackTexture();

    function clearRenderedMeshes() {
      for (const mesh of renderedMeshes) {
        scene.remove(mesh);
        mesh.geometry.dispose();
        if (Array.isArray(mesh.material)) {
          for (const material of mesh.material) material.dispose();
        } else {
          mesh.material.dispose();
        }
      }
      renderedMeshes = [];
    }

    function resize(): ViewMetrics {
      const width = Math.max(1, Math.floor(parent.clientWidth));
      const height = Math.max(1, Math.floor(parent.clientHeight));
      renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, 2.5));
      renderer.setSize(width, height, false);
      const visibleWidth = width;
      const visibleHeight = height;
      camera.left = visibleWidth / -2;
      camera.right = visibleWidth / 2;
      camera.top = visibleHeight / 2;
      camera.bottom = visibleHeight / -2;
      camera.updateProjectionMatrix();
      return {
        height,
        width,
        worldHeight: visibleHeight,
        worldWidth: visibleWidth
      };
    }

    function placeCamera() {
      camera.position.set(0, 0, 500);
      camera.lookAt(0, 0, 0);
    }

    async function renderCards() {
      const requestId = ++renderRequestId;
      const metrics = resize();
      placeCamera();
      const {
        cardByInstanceId: latestCardByInstanceId,
        filteredBoardObjects: latestFilteredBoardObjects,
        match: latestMatch,
        resolveSlotPosition: latestResolveSlotPosition
      } = latestRenderDataRef.current;

      const meshes = await Promise.all(latestFilteredBoardObjects.map(async object => {
        const renderedCard = object.cardInstanceId ? latestCardByInstanceId.get(object.cardInstanceId) ?? null : null;
        const isCardBack = object.lane === "hand" && !object.cardInstanceId;
        const isDeckBack = object.lane === "deck";
        const isCemetery = object.lane === "cemetery";
        const shouldRender = renderedCard || isCardBack || isDeckBack;

        if (!shouldRender) return null;

        const texture = renderedCard
          ? await loadCardTexture(getMatchCardImageUrls(latestMatch, renderedCard), loader, renderer)
          : backTexture;
        if (!texture || isDisposed) return null;

        const isSideways = isDeckBack || isCemetery;
        const worldCardWidth = CARD_WORLD_WIDTH;
        const worldCardHeight = CARD_WORLD_HEIGHT;
        const mesh = createPlane(texture, worldCardWidth, worldCardHeight);
        const position = latestResolveSlotPosition(object.slotId, object.xPercent, object.zPercent);
        mesh.position.set(
          (position.xPercent - 50) / 100 * metrics.worldWidth,
          (50 - position.zPercent) / 100 * metrics.worldHeight,
          Math.max(1, object.yDepth * heightScale)
        );
        mesh.rotation.z = isSideways ? -Math.PI / 2 : 0;

        return mesh;
      }));

      if (isDisposed || requestId !== renderRequestId) {
        for (const mesh of meshes) {
          mesh?.geometry.dispose();
          if (mesh && Array.isArray(mesh.material)) {
            for (const material of mesh.material) material.dispose();
          } else if (mesh) {
            mesh.material.dispose();
          }
        }
        return;
      }

      clearRenderedMeshes();
      for (const mesh of meshes) {
        if (mesh) {
          scene.add(mesh);
          renderedMeshes.push(mesh);
        }
      }
      renderer.render(scene, camera);
    }

    const scheduleRender = () => {
      void renderCards();
    };
    const resizeObserver = new ResizeObserver(() => {
      scheduleRender();
    });
    resizeObserver.observe(parent);
    window.addEventListener("resize", scheduleRender);
    document.addEventListener("fullscreenchange", scheduleRender);
    window.visualViewport?.addEventListener("resize", scheduleRender);

    void renderCards();

    return () => {
      isDisposed = true;
      renderRequestId += 1;
      resizeObserver.disconnect();
      window.removeEventListener("resize", scheduleRender);
      document.removeEventListener("fullscreenchange", scheduleRender);
      window.visualViewport?.removeEventListener("resize", scheduleRender);
      clearRenderedMeshes();
      renderer.dispose();
      backTexture.dispose();
    };
  }, [heightScale, renderSignature, resolveSlotPosition]);

  return <canvas ref={canvasRef} className="board-preview-3d__webgl-cards" aria-hidden="true" />;
}
