import { useEffect, useMemo, useRef, useState } from "react";
import * as THREE from "three";
import type { CardInstance } from "@ward/shared";
import type { AppMatchState } from "../../clientTypes";
import type { BoardObject } from "../boardPreview3dAdapter";
import { normalizeCardArtKey } from "../CardImagePreview";
import { getMatchCardImageUrls } from "../MatchCardImage";
import { getCardName } from "../../gameViewHelpers";
import {
  DEFAULT_IMAGE_SOURCE_CONTROLS,
  loadImageSourceControls,
  subscribeImageSourceControls
} from "../../imageSourceControls";

type BoardPreview3DWebGLCardsProps = {
  cardByInstanceId: Map<string, CardInstance>;
  filteredBoardObjects: BoardObject[];
  heightScale: number;
  zoneScale: number;
  compactCardTextures: boolean;
  match: AppMatchState;
  resolveSlotPosition: (slotId: string, fallbackX: number, fallbackZ: number) => { xPercent: number; zPercent: number };
};

const CARD_WORLD_WIDTH = 128;
const CARD_WORLD_HEIGHT = 179;
const cardTextureCache = new Map<string, Promise<THREE.Texture | null>>();
const HOLO_COLORS = [
  "rgba(125, 249, 255, 0.42)",
  "rgba(168, 85, 247, 0.36)",
  "rgba(244, 114, 182, 0.34)",
  "rgba(250, 204, 21, 0.3)",
  "rgba(74, 222, 128, 0.3)",
  "rgba(96, 165, 250, 0.34)"
];

type ViewMetrics = {
  height: number;
  width: number;
  worldHeight: number;
  worldWidth: number;
};

function createCardBackTexture(): THREE.CanvasTexture {
  const canvas = document.createElement("canvas");
  canvas.width = 512;
  canvas.height = 716;
  const context = canvas.getContext("2d");

  if (context) {
    const gradient = context.createLinearGradient(0, 0, canvas.width, canvas.height);
    gradient.addColorStop(0, "#0f172a");
    gradient.addColorStop(0.5, "#082f49");
    gradient.addColorStop(1, "#020617");
    context.fillStyle = gradient;
    context.fillRect(0, 0, canvas.width, canvas.height);
    context.strokeStyle = "rgba(125, 211, 252, 0.72)";
    context.lineWidth = 18;
    context.strokeRect(28, 28, canvas.width - 56, canvas.height - 56);
    context.strokeStyle = "rgba(250, 204, 21, 0.42)";
    context.lineWidth = 8;
    context.strokeRect(58, 58, canvas.width - 116, canvas.height - 116);
    context.fillStyle = "rgba(226, 232, 240, 0.92)";
    context.font = "900 54px system-ui, sans-serif";
    context.textAlign = "center";
    context.textBaseline = "middle";
    context.fillText("Ward", canvas.width / 2, canvas.height / 2 - 34);
    context.fillText("Nexus", canvas.width / 2, canvas.height / 2 + 34);
  }

  const texture = new THREE.CanvasTexture(canvas);
  texture.colorSpace = THREE.SRGBColorSpace;
  texture.generateMipmaps = true;
  texture.minFilter = THREE.LinearMipmapLinearFilter;
  texture.magFilter = THREE.LinearFilter;
  texture.anisotropy = 8;
  texture.needsUpdate = true;
  return texture;
}

function configureTexture(texture: THREE.Texture, renderer: THREE.WebGLRenderer): THREE.Texture {
  texture.colorSpace = THREE.SRGBColorSpace;
  texture.generateMipmaps = true;
  texture.minFilter = THREE.LinearMipmapLinearFilter;
  texture.magFilter = THREE.LinearFilter;
  texture.anisotropy = renderer.capabilities.getMaxAnisotropy();
  texture.needsUpdate = true;
  return texture;
}

async function loadCardTexture(urls: string[], loader: THREE.TextureLoader, renderer: THREE.WebGLRenderer): Promise<THREE.Texture | null> {
  for (const url of urls) {
    try {
      let cached = cardTextureCache.get(url);
      if (!cached) {
        cached = loader.loadAsync(url).then(texture => configureTexture(texture, renderer)).catch(() => null);
        cardTextureCache.set(url, cached);
      }
      const texture = await cached;
      if (texture) return texture;
    } catch {
      // Try the next candidate generated by MatchCardImage.
    }
  }

  return null;
}

function hashSeed(seed: string): number {
  let hash = 2166136261;

  for (let index = 0; index < seed.length; index += 1) {
    hash ^= seed.charCodeAt(index);
    hash = Math.imul(hash, 16777619);
  }

  return hash >>> 0;
}

function createSeededRandom(seed: string): () => number {
  let state = hashSeed(seed) || 1;

  return () => {
    state ^= state << 13;
    state ^= state >>> 17;
    state ^= state << 5;
    return ((state >>> 0) % 10000) / 10000;
  };
}

function createHolographicCardTexture(baseTexture: THREE.Texture, renderer: THREE.WebGLRenderer, seed: string): THREE.Texture {
  const source = baseTexture.image as CanvasImageSource & {
    naturalHeight?: number;
    naturalWidth?: number;
    height?: number;
    width?: number;
  };
  const width = Math.max(1, Math.floor(source.naturalWidth ?? source.width ?? 512));
  const height = Math.max(1, Math.floor(source.naturalHeight ?? source.height ?? 716));
  const canvas = document.createElement("canvas");
  canvas.width = width;
  canvas.height = height;

  const context = canvas.getContext("2d");

  if (!context) {
    return baseTexture;
  }

  const random = createSeededRandom(seed);
  context.drawImage(source, 0, 0, width, height);

  const sweep = context.createLinearGradient(0, height, width, 0);
  sweep.addColorStop(0, "rgba(125, 249, 255, 0)");
  sweep.addColorStop(0.22, "rgba(125, 249, 255, 0.28)");
  sweep.addColorStop(0.42, "rgba(244, 114, 182, 0.22)");
  sweep.addColorStop(0.62, "rgba(250, 204, 21, 0.2)");
  sweep.addColorStop(0.82, "rgba(168, 85, 247, 0.26)");
  sweep.addColorStop(1, "rgba(125, 249, 255, 0)");

  context.globalCompositeOperation = "screen";
  context.fillStyle = sweep;
  context.fillRect(0, 0, width, height);

  for (let index = 0; index < 44; index += 1) {
    const x = random() * width;
    const y = random() * height;
    const radius = (0.04 + random() * 0.13) * Math.min(width, height);
    const sides = 3 + Math.floor(random() * 3);
    const angleOffset = random() * Math.PI * 2;

    context.beginPath();
    for (let pointIndex = 0; pointIndex < sides; pointIndex += 1) {
      const angle = angleOffset + (pointIndex / sides) * Math.PI * 2;
      const px = x + Math.cos(angle) * radius * (0.45 + random() * 0.55);
      const py = y + Math.sin(angle) * radius * (0.45 + random() * 0.55);

      if (pointIndex === 0) {
        context.moveTo(px, py);
      } else {
        context.lineTo(px, py);
      }
    }
    context.closePath();
    context.fillStyle = HOLO_COLORS[index % HOLO_COLORS.length] ?? HOLO_COLORS[0];
    context.globalAlpha = 0.32 + random() * 0.22;
    context.fill();
  }

  context.globalAlpha = 1;
  context.globalCompositeOperation = "lighter";
  for (let index = 0; index < 90; index += 1) {
    const x = random() * width;
    const y = random() * height;
    const size = 0.75 + random() * 2.25;

    context.fillStyle = `rgba(255, 255, 255, ${0.12 + random() * 0.24})`;
    context.fillRect(x, y, size, size);
  }

  context.globalCompositeOperation = "source-over";

  return configureTexture(new THREE.CanvasTexture(canvas), renderer);
}

async function loadCardTextureForCard(
  match: AppMatchState,
  card: CardInstance,
  loader: THREE.TextureLoader,
  renderer: THREE.WebGLRenderer,
  compactCardTextures: boolean,
  imageUrls: string[]
): Promise<THREE.Texture | null> {
  const artKey = normalizeCardArtKey(card.artKey);
  const holoEnabled = artKey === "holo" || artKey === "zero-art-holo";
  const baseTexture = await loadCardTexture(imageUrls, loader, renderer);

  if (!baseTexture) {
    return baseTexture;
  }

  let texture: THREE.Texture = baseTexture;
  if (compactCardTextures) {
    const compactKey = `compact:${match.matchId}:${card.instanceId}:${artKey}`;
    let compactCached = cardTextureCache.get(compactKey);
    if (!compactCached) {
      compactCached = Promise.resolve(createCompactCardTexture(baseTexture, getCardName(match, card), renderer));
      cardTextureCache.set(compactKey, compactCached);
    }
    const compactTexture = await compactCached;
    if (compactTexture) texture = compactTexture;
  }

  if (!holoEnabled) {
    return texture;
  }

  const cacheKey = `holo:${match.matchId}:${card.instanceId}:${artKey}`;
  let cached = cardTextureCache.get(cacheKey);

  if (!cached) {
    cached = Promise.resolve(createHolographicCardTexture(texture, renderer, cacheKey));
    cardTextureCache.set(cacheKey, cached);
  }

  return cached;
}

function createCompactCardTexture(baseTexture: THREE.Texture, cardName: string, renderer: THREE.WebGLRenderer): THREE.Texture {
  const source = baseTexture.image as CanvasImageSource & { naturalHeight?: number; naturalWidth?: number; height?: number; width?: number; };
  const canvas = document.createElement("canvas");
  canvas.width = 512;
  canvas.height = 716;
  const context = canvas.getContext("2d");
  if (!context) return baseTexture;

  context.fillStyle = "#020617";
  context.fillRect(0, 0, canvas.width, canvas.height);
  context.drawImage(source, 24, 82, canvas.width - 48, canvas.height - 180);
  context.fillStyle = "rgba(3, 7, 18, 0.95)";
  context.fillRect(16, 16, canvas.width - 32, 56);
  context.strokeStyle = "rgba(148, 163, 184, 0.9)";
  context.lineWidth = 2;
  context.strokeRect(16, 16, canvas.width - 32, 56);
  context.fillStyle = "#f8fafc";
  context.font = "700 28px system-ui, sans-serif";
  context.textAlign = "center";
  context.textBaseline = "middle";
  context.fillText(cardName.slice(0, 30), canvas.width / 2, 44);
  context.fillStyle = "rgba(15, 23, 42, 0.9)";
  context.fillRect(16, canvas.height - 84, canvas.width - 32, 56);
  context.fillStyle = "#e2e8f0";
  context.font = "600 22px system-ui, sans-serif";
  context.fillText("Tap to inspect", canvas.width / 2, canvas.height - 56);
  return configureTexture(new THREE.CanvasTexture(canvas), renderer);
}

function createPlane(texture: THREE.Texture, width: number, height: number): THREE.Mesh {
  const geometry = new THREE.PlaneGeometry(width, height);
  const material = new THREE.MeshBasicMaterial({
    map: texture,
    side: THREE.DoubleSide,
    toneMapped: false,
    transparent: true
  });
  const mesh = new THREE.Mesh(geometry, material);
  return mesh;
}

export function BoardPreview3DWebGLCards({
  cardByInstanceId,
  filteredBoardObjects,
  heightScale,
  zoneScale,
  compactCardTextures,
  match,
  resolveSlotPosition
}: BoardPreview3DWebGLCardsProps) {
  const [boardControls, setBoardControls] = useState(() => loadImageSourceControls().board3d);
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const latestRenderDataRef = useRef({
    cardByInstanceId,
    filteredBoardObjects,
    match,
    resolveSlotPosition
  });
  latestRenderDataRef.current = {
    cardByInstanceId,
    filteredBoardObjects,
    match,
    resolveSlotPosition
  };

  useEffect(() => {
    const refresh = () => setBoardControls(loadImageSourceControls().board3d);
    return subscribeImageSourceControls(refresh);
  }, []);

  const activeBoardControls = boardControls ?? DEFAULT_IMAGE_SOURCE_CONTROLS.board3d;
  const renderSignature = useMemo(
    () => filteredBoardObjects
      .map(object => {
        const renderedCard = object.cardInstanceId ? cardByInstanceId.get(object.cardInstanceId) ?? null : null;
        const urls = renderedCard ? getMatchCardImageUrls(match, renderedCard).join(",") : "";
        return [
          object.id,
          object.slotId,
          object.lane,
          object.cardInstanceId ?? "back",
          renderedCard?.artKey ?? "default",
          object.xPercent.toFixed(3),
          object.zPercent.toFixed(3),
          object.yDepth.toFixed(3),
          urls,
          activeBoardControls.priority.join(">"),
          activeBoardControls.scale.toString()
        ].join(":");
      })
      .join("|"),
    [activeBoardControls.priority, activeBoardControls.scale, cardByInstanceId, filteredBoardObjects, match]
  );

  useEffect(() => {
    const canvas = canvasRef.current;
    const parent = canvas?.parentElement;
    if (!canvas || !parent) return;

    let isDisposed = false;
    const renderer = new THREE.WebGLRenderer({
      alpha: true,
      antialias: true,
      canvas,
      powerPreference: "high-performance"
    });
    renderer.outputColorSpace = THREE.SRGBColorSpace;
    renderer.setClearColor(0x000000, 0);
    renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, 2.5));

    const scene = new THREE.Scene();
    const camera = new THREE.OrthographicCamera(
      -1,
      1,
      1,
      -1,
      0.1,
      1000
    );
    const loader = new THREE.TextureLoader();
    let renderedMeshes: THREE.Mesh[] = [];
    let renderRequestId = 0;
    const backTexture = createCardBackTexture();

    function clearRenderedMeshes() {
      for (const mesh of renderedMeshes) {
        scene.remove(mesh);
        mesh.geometry.dispose();
        if (Array.isArray(mesh.material)) {
          for (const material of mesh.material) material.dispose();
        } else {
          mesh.material.dispose();
        }
      }
      renderedMeshes = [];
    }

    function resize(): ViewMetrics {
      const width = Math.max(1, Math.floor(parent.clientWidth));
      const height = Math.max(1, Math.floor(parent.clientHeight));
      renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, 2.5));
      renderer.setSize(width, height, false);
      const visibleWidth = width;
      const visibleHeight = height;
      camera.left = visibleWidth / -2;
      camera.right = visibleWidth / 2;
      camera.top = visibleHeight / 2;
      camera.bottom = visibleHeight / -2;
      camera.updateProjectionMatrix();
      return {
        height,
        width,
        worldHeight: visibleHeight,
        worldWidth: visibleWidth
      };
    }

    function placeCamera() {
      camera.position.set(0, 0, 500);
      camera.lookAt(0, 0, 0);
    }

    async function renderCards() {
      const requestId = ++renderRequestId;
      const metrics = resize();
      placeCamera();
      const {
        cardByInstanceId: latestCardByInstanceId,
        filteredBoardObjects: latestFilteredBoardObjects,
        match: latestMatch,
        resolveSlotPosition: latestResolveSlotPosition
      } = latestRenderDataRef.current;

      const meshes = await Promise.all(latestFilteredBoardObjects.map(async object => {
        const renderedCard = object.cardInstanceId ? latestCardByInstanceId.get(object.cardInstanceId) ?? null : null;
        const isCardBack = object.lane === "hand" && !object.cardInstanceId;
        const isDeckBack = object.lane === "deck";
        const isCemetery = object.lane === "cemetery";
        const shouldRender = renderedCard || isCardBack || isDeckBack;

        if (!shouldRender) return null;

        const texture = renderedCard
          ? await loadCardTextureForCard(
            latestMatch,
            renderedCard,
            loader,
            renderer,
            compactCardTextures,
            getMatchCardImageUrls(latestMatch, renderedCard)
          )
          : backTexture;
        if (!texture || isDisposed) return null;

        const isSideways = isDeckBack || isCemetery;
        const worldCardWidth = CARD_WORLD_WIDTH;
        const worldCardHeight = CARD_WORLD_HEIGHT;
        const mesh = createPlane(texture, worldCardWidth, worldCardHeight);
        const position = latestResolveSlotPosition(object.slotId, object.xPercent, object.zPercent);
        mesh.position.set(
          ((position.xPercent - 50) * zoneScale) / 100 * metrics.worldWidth,
          ((50 - position.zPercent) * zoneScale) / 100 * metrics.worldHeight,
          Math.max(1, object.yDepth * heightScale)
        );
        mesh.rotation.z = isSideways ? -Math.PI / 2 : 0;

        return mesh;
      }));

      if (isDisposed || requestId !== renderRequestId) {
        for (const mesh of meshes) {
          mesh?.geometry.dispose();
          if (mesh && Array.isArray(mesh.material)) {
            for (const material of mesh.material) material.dispose();
          } else if (mesh) {
            mesh.material.dispose();
          }
        }
        return;
      }

      clearRenderedMeshes();
      for (const mesh of meshes) {
        if (mesh) {
          scene.add(mesh);
          renderedMeshes.push(mesh);
        }
      }
      renderer.render(scene, camera);
    }

    const scheduleRender = () => {
      void renderCards();
    };
    const resizeObserver = typeof ResizeObserver !== "undefined"
      ? new ResizeObserver(() => {
          scheduleRender();
        })
      : null;
    resizeObserver?.observe(parent);
    window.addEventListener("resize", scheduleRender);
    document.addEventListener("fullscreenchange", scheduleRender);
    window.visualViewport?.addEventListener("resize", scheduleRender);

    void renderCards();

    return () => {
      isDisposed = true;
      renderRequestId += 1;
      resizeObserver?.disconnect();
      window.removeEventListener("resize", scheduleRender);
      document.removeEventListener("fullscreenchange", scheduleRender);
      window.visualViewport?.removeEventListener("resize", scheduleRender);
      clearRenderedMeshes();
      renderer.dispose();
      backTexture.dispose();
    };
  }, [heightScale, renderSignature, resolveSlotPosition]);

  return <canvas ref={canvasRef} className="board-preview-3d__webgl-cards" aria-hidden="true" />;
}
